; Peru Cyber Red-Black Color Scheme
[colors]
background = #080808
background-alt = #121212
foreground = #ffffff
primary = #ff1a1a
secondary = #ff4d4d
tertiary = #ffffff
highlight-low = #121212
highlight-med = #222222
highlight-high = #333333
alert = #ff1a1a
disabled = #555555
