# Peru Cyber Kitty Theme
background            #080808
foreground            #ffffff
cursor                #ff1a1a
cursor_text_color     #000000
selection_background  #ff1a1a
selection_foreground  #ffffff

# Tab bar colors
active_tab_foreground   #ffffff
active_tab_background   #ff1a1a
inactive_tab_foreground #888888
inactive_tab_background #121212

# Terminal colors
# Black
color0  #121212
color8  #333333

# Red
color1  #ff1a1a
color9  #ff4d4d

# Green
color2  #00e676
color10 #66ffa6

# Yellow
color3  #ffd600
color11 #ffff52

# Blue
color4  #2979ff
color12 #75a7ff

# Magenta
color5  #d500f9
color13 #ff54ff

# Cyan
color6  #00e5ff
color14 #69f0ff

# White
color7  #e0e0e0
color15 #ffffff
