# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F8E9E9
background         #29292A
cursor             #928A8D

active_tab_foreground     #29292A
active_tab_background     #F8E9E9
inactive_tab_foreground   #F8E9E9
inactive_tab_background   #29292A

active_border_color   #F8E9E9
inactive_border_color #29292A
bell_border_color     #1E1F23

color0      #4E4E50
color1		#1E1F23
color2		#212125
color3		#4E3E3E
color4		#8D423C
color5		#6D5F62
color6		#B09191
color7		#ECD7D7
color8		#A69797
color9		#28292F
color10		#2C2C31
color11		#685353
color12		#BC5850
color13		#917E82
color14		#EBC1C1
color15		#ECD7D7
